### ISSUE TITLE
Support time shifting

### ISSUE THREAD

**Issue by Fleker** [Fleker/ChannelSurfer#11]
I just realized the `TvInputManager` has options for time shifting.

There should be support for `notifyTimeShiftStatusChanged()` and perhaps overriding the other methods for services to implement time shift operations

(These only seem to be available in API 23)

**Comment by mattgorski** [comment]
Cant wait to see the development of timeshifting 3rd party live channels apps in Android TV 6+!!!!

**Comment by Fleker** [comment]
Although I can use the TimeShiftable interface in my service, I'd like to push this into the `ExoPlayerTvProvider` so it's always available.
