### ISSUE TITLE
Local files don't play in 0.2.3-beta-1 on Sony Android TV

### ISSUE THREAD

**Issue by nextux** [Fleker/ChannelSurfer#15]
androidtv.news didn't play at all.

Dance Party shows the yellow background with "We're playing some music!" but no music plays.

Model: Bravia 2015 W800C
Version: 5.1.1
Build: SVPDTV15_PA-user 5.1.1 LMY48E.S127 3.017 release-keys

**Comment by Fleker** [comment]
Yeah I'll have to figure that out. Sony TVs have been a unique case. The
local video should work on Android 5.1 and below (else you'll have to
manually grant storage permissions).

Are you getting popup messages when you change channels?

**Comment by nextux** [comment]
Yes, the gray pop ups are working perfectly.  The media itself is not playing.

As this is Android 5.1.1, there is no way to modify permissions.  Thought this might be a sticking point for people using your library to create channels that use other content such as local media or music.

**Comment by Fleker** [comment]
If it is 5.1.1, the permission should be granted automatically. The playback issues could be coming from the Sony implementation. Can you check if the media files are copied correctly in the file browser? `/storage/emulated/0/channelsurfer/` is the folder.

**Comment by nextux** [comment]
There are no files in that folder.  The folder exists however.  I can see from the message at the bottom of the screen as I go to each channel that it is trying to play a file within that folder.

**Comment by Fleker** [comment]
Yes it is trying to play that file. If it doesn't exist, that's certainly
an odd problem. Can you resync again through Channel Sources and see if the
files exist?

**Comment by nextux** [comment]
Worked fine the second time around.  Seems like the problem is now solved.

**Comment by Fleker** [comment]
Then I may need to adjust the file copy system so that it works the first
time.
