### ISSUE TITLE
Sample app doesn't seem to include any tutorial on adding individual channel logos for each channel

### ISSUE THREAD

**Issue by nextux** [Fleker/ChannelSurfer#4]
Reading the source code for the sample app, it doesn't appear there is an easy way to point a channel to a file within the res folder to use for a channel logo. I imagine if a traditional TV network wanted to use the code for their own app they may want to be able to distinguish different channels with a custom logo.

**Comment by Fleker** [comment]
Okay. I should be able to expose that functionality.

**Comment by Fleker** [comment]
Added this
