### ISSUE TITLE
Improved sample app

### ISSUE THREAD

**Issue by Fleker** [Fleker/ChannelSurfer#6]
Add support for different types of playback in the sample app to show developers how they'd be done:
- Websites
- Music
- Local video
- Daydreams (?)

**Comment by birkir** [comment]
Was thinking about porting my Plex bundle to a Live Channels app for Android TV. 

I would require the user to enter username/password before using the app, then I could display list of channels available to him. To watch a stream, making a request for a token to unlock the stream for some amount of time (few hours usually) is necessary.

I'm not experienced android developer but I'm just asking for a theory answer how the workflow of this kind of solution would be or possible at all.

https://github.com/birkir/OZ.bundle/blob/master/Contents/Code/__init__.py#L374

**Comment by Fleker** [comment]
This would definitely be possible. When initially setting up the channels, you can have a custom setup activity. Your activity can have any sort of UI, including a dialog which asks for username and password. If that connection is successful, you should be able to play media. When the token expires, you should be able to request a new one in your tv input service (probably in the `onTune` method).

I'm not familiar with Plex and their APIs specifically, but the framework around it should definitely be able to help you.

**Comment by birkir** [comment]
Thanks. Awesome job man! :+1:
