### ISSUE TITLE
Can't get it to build for Android 5.1.1 SDK

### ISSUE THREAD

**Issue by nextux** [Fleker/ChannelSurfer#7]
I have downloaded your files as they are.  Trying to compile and install directly gives me a "Parse Error".  I thought it might be that Android Studio isn't using the correct SDK version.  I changed in the build.gradle files the SDK version to 22.  Android Studio reports that it has built the APK.  Upon attempting to install, the package installer crashes.

Any reason your prebuilt apk runs without issues and the one I am trying to build is failing?

**Comment by Fleker** [comment]
I've got no clue. I compiled the prebuilt apk straight from the source. Everything should be there. You probably shouldn't change the `targetSdkVersion`.

Try this: http://stackoverflow.com/questions/29682002/error-on-installing-apk-parsing-the-package?rq=1

**Comment by nextux** [comment]
That seemed to solve the intial issue of the Parse Error.  However I still am unable to install the built apk.  The package manager on my Sony Android TV crashes in the middle of the install....whereas your file works without issues....only thing I have done different is remove the line "apply from: 'maven-push.gradle'" from library/build.gradle as it was failing everytime.

**Comment by nextux** [comment]
This is with package built on my Mac using Android Studio, as well as using BuddyBuild service.  Both packages behave the same on my TV.

**Comment by Fleker** [comment]
Yes the `maven-push.gradle` will have to be removed as that's needed to update maven, but the authentication properties are not included. Does removing this line and compiling create a workable apk?

**Comment by nextux** [comment]
I'm unable to test this out as when I go to install the apk, my Sony Bravia's Package Installer app is crashing partway through.  Your apk from the releases section is working perfectly though.  The only source change I had made is removing that one line, so in theory, the apk should be the same.

**Comment by Fleker** [comment]
Do you have a second Android TV device you can test your compiled app with?

**Comment by nextux** [comment]
I do....just need to set it up again.  I'll update results here.

**Comment by Fleker** [comment]
Has there been an update?

**Comment by nextux** [comment]
Haven't had a chance to get it out and plug it in.... (Real life) but all
your apks work fine on either so I am putting it down to my build setup.  I
will look into it more hopefully tonight if I can get a moment.

**Comment by nextux** [comment]
My build works on my Nexus player perfectly which is running Marshmallow. So I'll need to look at why on my end.
